version: "3.8"

services:
    postgres:
        image: postgres:latest
        ports:
            - "3005:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=clave123
            - POSTGRES_DB=sigeco_bd
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
